services:
  hicore:
    build: .
    container_name: unsiao-hicore
    ports:
      - "8000:8000"
    volumes:
      # 持久化数据库目录和工作目录
      - ./databases:/app/databases
      - ./work:/app/work
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
